<?php

use App\Model\Country;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = date('Y-m-d H:i:s');
        activity()->disableLogging();
        DB::table('countries')->delete();

        $country = [
            ['id' => '1',  'name' => 'Afghanistan', 'code' => 'AF', 'lang' => strtolower('AF'), 'phone_code' => '93', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '2',  'name' => 'Albania', 'code' => 'AL', 'lang' => strtolower('AL'), 'phone_code' => '355', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '3',  'name' => 'Algeria', 'code' => 'DZ', 'lang' => strtolower('DZ'), 'phone_code' => '213', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '4',  'name' => 'American Samoa', 'code' => 'AS', 'lang' => strtolower('AS'), 'phone_code' => '1684', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '5',  'name' => 'Andorra', 'code' => 'AD', 'lang' => strtolower('AD'), 'phone_code' => '376', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '6',  'name' => 'Angola', 'code' => 'AO', 'lang' => strtolower('AO'), 'phone_code' => '244', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '7',  'name' => 'Anguilla', 'code' => 'AI', 'lang' => strtolower('AI'), 'phone_code' => '1264', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '8',  'name' => 'Antarctica', 'code' => 'AQ', 'lang' => strtolower('AQ'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '9',  'name' => 'Antigua And Barbuda', 'code' => 'AG', 'lang' => strtolower('AG'), 'phone_code' => '1268', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '10',  'name' => 'Argentina', 'code' => 'AR', 'lang' => strtolower('AR'), 'phone_code' => '54', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '11',  'name' => 'Armenia', 'code' => 'AM', 'lang' => strtolower('AM'), 'phone_code' => '374', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '12',  'name' => 'Aruba', 'code' => 'AW', 'lang' => strtolower('AW'), 'phone_code' => '297', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '13',  'name' => 'Australia', 'code' => 'AU', 'lang' => strtolower('AU'), 'phone_code' => '61', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '14',  'name' => 'Austria', 'code' => 'AT', 'lang' => strtolower('AT'), 'phone_code' => '43', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '15',  'name' => 'Azerbaijan', 'code' => 'AZ', 'lang' => strtolower('AZ'), 'phone_code' => '994', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '16',  'name' => 'Bahamas The', 'code' => 'BS', 'lang' => strtolower('BS'), 'phone_code' => '1242', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '17',  'name' => 'Bahrain', 'code' => 'BH', 'lang' => strtolower('BH'), 'phone_code' => '973', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '18',  'name' => 'Bangladesh', 'code' => 'BD', 'lang' => strtolower('BD'), 'phone_code' => '880', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '19',  'name' => 'Barbados', 'code' => 'BB', 'lang' => strtolower('BB'), 'phone_code' => '1246', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '20',  'name' => 'Belarus', 'code' => 'BY', 'lang' => strtolower('BY'), 'phone_code' => '375', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '21',  'name' => 'Belgium', 'code' => 'BE', 'lang' => strtolower('BE'), 'phone_code' => '32', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '22',  'name' => 'Belize', 'code' => 'BZ', 'lang' => strtolower('BZ'), 'phone_code' => '501', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '23',  'name' => 'Benin', 'code' => 'BJ', 'lang' => strtolower('BJ'), 'phone_code' => '229', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '24',  'name' => 'Bermuda', 'code' => 'BM', 'lang' => strtolower('BM'), 'phone_code' => '1441', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '25',  'name' => 'Bhutan', 'code' => 'BT', 'lang' => strtolower('BT'), 'phone_code' => '975', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '26',  'name' => 'Bolivia', 'code' => 'BO', 'lang' => strtolower('BO'), 'phone_code' => '591', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '27',  'name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'lang' => strtolower('BA'), 'phone_code' => '387', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '28',  'name' => 'Botswana', 'code' => 'BW', 'lang' => strtolower('BW'), 'phone_code' => '267', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '29',  'name' => 'Bouvet Island', 'code' => 'BV', 'lang' => strtolower('BV'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '30',  'name' => 'Brazil', 'code' => 'BR', 'lang' => strtolower('BR'), 'phone_code' => '55', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '31',  'name' => 'British Indian Ocean Territory', 'code' => 'IO', 'lang' => strtolower('IO'), 'phone_code' => '246', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '32',  'name' => 'Brunei', 'code' => 'BN', 'lang' => strtolower('BN'), 'phone_code' => '673', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '33',  'name' => 'Bulgaria', 'code' => 'BG', 'lang' => strtolower('BG'), 'phone_code' => '359', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '34',  'name' => 'Burkina Faso', 'code' => 'BF', 'lang' => strtolower('BF'), 'phone_code' => '226', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '35',  'name' => 'Burundi', 'code' => 'BI', 'lang' => strtolower('BI'), 'phone_code' => '257', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '36',  'name' => 'Cambodia', 'code' => 'KH', 'lang' => strtolower('KH'), 'phone_code' => '855', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '37',  'name' => 'Cameroon', 'code' => 'CM', 'lang' => strtolower('CM'), 'phone_code' => '237', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '38',  'name' => 'Canada', 'code' => 'CA', 'lang' => strtolower('CA'), 'phone_code' => '1', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '39',  'name' => 'Cape Verde', 'code' => 'CV', 'lang' => strtolower('CV'), 'phone_code' => '238', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '40',  'name' => 'Cayman Islands', 'code' => 'KY', 'lang' => strtolower('KY'), 'phone_code' => '1345', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '41',  'name' => 'Central African Republic', 'code' => 'CF', 'lang' => strtolower('CF'), 'phone_code' => '236', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '42',  'name' => 'Chad', 'code' => 'TD', 'lang' => strtolower('TD'), 'phone_code' => '235', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '43',  'name' => 'Chile', 'code' => 'CL', 'lang' => strtolower('CL'), 'phone_code' => '56', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '44',  'name' => 'China', 'code' => 'CN', 'lang' => strtolower('CN'), 'phone_code' => '86', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '45',  'name' => 'Christmas Island', 'code' => 'CX', 'lang' => strtolower('CX'), 'phone_code' => '61', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '46',  'name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'lang' => strtolower('CC'), 'phone_code' => '672', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '47',  'name' => 'Colombia', 'code' => 'CO', 'lang' => strtolower('CO'), 'phone_code' => '57', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '48',  'name' => 'Comoros', 'code' => 'KM', 'lang' => strtolower('KM'), 'phone_code' => '269', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '49',  'name' => 'Republic Of The Congo', 'code' => 'CG', 'lang' => strtolower('CG'), 'phone_code' => '242', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '50',  'name' => 'Democratic Republic Of The Congo', 'code' => 'CD', 'lang' => strtolower('CD'), 'phone_code' => '242', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '51',  'name' => 'Cook Islands', 'code' => 'CK', 'lang' => strtolower('CK'), 'phone_code' => '682', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '52',  'name' => 'Costa Rica', 'code' => 'CR', 'lang' => strtolower('CR'), 'phone_code' => '506', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '53',  'name' => 'Cote D\'Ivoire (Ivory Coast)', 'code' => 'CI', 'lang' => strtolower('CI'), 'phone_code' => '225', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '54',  'name' => 'Croatia (Hrvatska)', 'code' => 'HR', 'lang' => strtolower('HR'), 'phone_code' => '385', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '55',  'name' => 'Cuba', 'code' => 'CU', 'lang' => strtolower('CU'), 'phone_code' => '53', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '56',  'name' => 'Cyprus', 'code' => 'CY', 'lang' => strtolower('CY'), 'phone_code' => '357', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '57',  'name' => 'Czech Republic', 'code' => 'CZ', 'lang' => strtolower('CZ'), 'phone_code' => '420', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '58',  'name' => 'Denmark', 'code' => 'DK', 'lang' => strtolower('DK'), 'phone_code' => '45', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '59',  'name' => 'Djibouti', 'code' => 'DJ', 'lang' => strtolower('DJ'), 'phone_code' => '253', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '60',  'name' => 'Dominica', 'code' => 'DM', 'lang' => strtolower('DM'), 'phone_code' => '1767', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '61',  'name' => 'Dominican Republic', 'code' => 'DO', 'lang' => strtolower('DO'), 'phone_code' => '1809', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '62',  'name' => 'East Timor', 'code' => 'TP', 'lang' => strtolower('TP'), 'phone_code' => '670', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '63',  'name' => 'Ecuador', 'code' => 'EC', 'lang' => strtolower('EC'), 'phone_code' => '593', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '64',  'name' => 'Egypt', 'code' => 'EG', 'lang' => strtolower('EG'), 'phone_code' => '20', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '65',  'name' => 'El Salvador', 'code' => 'SV', 'lang' => strtolower('SV'), 'phone_code' => '503', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '66',  'name' => 'Equatorial Guinea', 'code' => 'GQ', 'lang' => strtolower('GQ'), 'phone_code' => '240', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '67',  'name' => 'Eritrea', 'code' => 'ER', 'lang' => strtolower('ER'), 'phone_code' => '291', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '68',  'name' => 'Estonia', 'code' => 'EE', 'lang' => strtolower('EE'), 'phone_code' => '372', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '69',  'name' => 'Ethiopia', 'code' => 'ET', 'lang' => strtolower('ET'), 'phone_code' => '251', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '70',  'name' => 'External Territories of Australia', 'code' => 'XA', 'lang' => strtolower('XA'), 'phone_code' => '61', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '71',  'name' => 'Falkland Islands', 'code' => 'FK', 'lang' => strtolower('FK'), 'phone_code' => '500', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '72',  'name' => 'Faroe Islands', 'code' => 'FO', 'lang' => strtolower('FO'), 'phone_code' => '298', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '73',  'name' => 'Fiji Islands', 'code' => 'FJ', 'lang' => strtolower('FJ'), 'phone_code' => '679', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '74',  'name' => 'Finland', 'code' => 'FI', 'lang' => strtolower('FI'), 'phone_code' => '358', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '75',  'name' => 'France', 'code' => 'FR', 'lang' => strtolower('FR'), 'phone_code' => '33', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '76',  'name' => 'French Guiana', 'code' => 'GF', 'lang' => strtolower('GF'), 'phone_code' => '594', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '77',  'name' => 'French Polynesia', 'code' => 'PF', 'lang' => strtolower('PF'), 'phone_code' => '689', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '78',  'name' => 'French Southern Territories', 'code' => 'TF', 'lang' => strtolower('TF'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '79',  'name' => 'Gabon', 'code' => 'GA', 'lang' => strtolower('GA'), 'phone_code' => '241', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '80',  'name' => 'Gambia The', 'code' => 'GM', 'lang' => strtolower('GM'), 'phone_code' => '220', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '81',  'name' => 'Georgia', 'code' => 'GE', 'lang' => strtolower('GE'), 'phone_code' => '995', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '82',  'name' => 'Germany', 'code' => 'DE', 'lang' => strtolower('DE'), 'phone_code' => '49', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '83',  'name' => 'Ghana', 'code' => 'GH', 'lang' => strtolower('GH'), 'phone_code' => '233', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '84',  'name' => 'Gibraltar', 'code' => 'GI', 'lang' => strtolower('GI'), 'phone_code' => '350', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '85',  'name' => 'Greece', 'code' => 'GR', 'lang' => strtolower('GR'), 'phone_code' => '30', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '86',  'name' => 'Greenland', 'code' => 'GL', 'lang' => strtolower('GL'), 'phone_code' => '299', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '87',  'name' => 'Grenada', 'code' => 'GD', 'lang' => strtolower('GD'), 'phone_code' => '1473', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '88',  'name' => 'Guadeloupe', 'code' => 'GP', 'lang' => strtolower('GP'), 'phone_code' => '590', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '89',  'name' => 'Guam', 'code' => 'GU', 'lang' => strtolower('GU'), 'phone_code' => '1671', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '90',  'name' => 'Guatemala', 'code' => 'GT', 'lang' => strtolower('GT'), 'phone_code' => '502', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '91',  'name' => 'Guernsey and Alderney', 'code' => 'XU', 'lang' => strtolower('XU'), 'phone_code' => '44', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '92',  'name' => 'Guinea', 'code' => 'GN', 'lang' => strtolower('GN'), 'phone_code' => '224', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '93',  'name' => 'Guinea-Bissau', 'code' => 'GW', 'lang' => strtolower('GW'), 'phone_code' => '245', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '94',  'name' => 'Guyana', 'code' => 'GY', 'lang' => strtolower('GY'), 'phone_code' => '592', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '95',  'name' => 'Haiti', 'code' => 'HT', 'lang' => strtolower('HT'), 'phone_code' => '509', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '96',  'name' => 'Heard and McDonald Islands', 'code' => 'HM', 'lang' => strtolower('HM'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '97',  'name' => 'Honduras', 'code' => 'HN', 'lang' => strtolower('HN'), 'phone_code' => '504', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '98',  'name' => 'Hong Kong S.A.R.', 'code' => 'HK', 'lang' => strtolower('HK'), 'phone_code' => '852', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '99',  'name' => 'Hungary', 'code' => 'HU', 'lang' => strtolower('HU'), 'phone_code' => '36', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '100',  'name' => 'Iceland', 'code' => 'IS', 'lang' => strtolower('IS'), 'phone_code' => '354', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '101',  'name' => 'India', 'code' => 'IN', 'lang' => strtolower('IN'), 'phone_code' => '91', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '102',  'name' => 'Indonesia', 'code' => 'ID', 'lang' => strtolower('ID'), 'phone_code' => '62', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '103',  'name' => 'Iran', 'code' => 'IR', 'lang' => strtolower('fa'), 'phone_code' => '98', 'color' => '#f45d22', 'is_active' => 1, 'created_at' => $now],
            ['id' => '104',  'name' => 'Iraq', 'code' => 'IQ', 'lang' => strtolower('IQ'), 'phone_code' => '964', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '105',  'name' => 'Ireland', 'code' => 'IE', 'lang' => strtolower('IE'), 'phone_code' => '353', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '106',  'name' => 'Israel', 'code' => 'IL', 'lang' => strtolower('IL'), 'phone_code' => '972', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '107',  'name' => 'Italy', 'code' => 'IT', 'lang' => strtolower('IT'), 'phone_code' => '39', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '108',  'name' => 'Jamaica', 'code' => 'JM', 'lang' => strtolower('JM'), 'phone_code' => '1876', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '109',  'name' => 'Japan', 'code' => 'JP', 'lang' => strtolower('JP'), 'phone_code' => '81', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '110',  'name' => 'Jersey', 'code' => 'XJ', 'lang' => strtolower('XJ'), 'phone_code' => '44', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '111',  'name' => 'Jordan', 'code' => 'JO', 'lang' => strtolower('JO'), 'phone_code' => '962', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '112',  'name' => 'Kazakhstan', 'code' => 'KZ', 'lang' => strtolower('KZ'), 'phone_code' => '7', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '113',  'name' => 'Kenya', 'code' => 'KE', 'lang' => strtolower('KE'), 'phone_code' => '254', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '114',  'name' => 'Kiribati', 'code' => 'KI', 'lang' => strtolower('KI'), 'phone_code' => '686', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '115',  'name' => 'Korea North', 'code' => 'KP', 'lang' => strtolower('KP'), 'phone_code' => '850', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '116',  'name' => 'Korea South', 'code' => 'KR', 'lang' => strtolower('KR'), 'phone_code' => '82', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '117',  'name' => 'Kuwait', 'code' => 'KW', 'lang' => strtolower('KW'), 'phone_code' => '965', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '118',  'name' => 'Kyrgyzstan', 'code' => 'KG', 'lang' => strtolower('KG'), 'phone_code' => '996', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '119',  'name' => 'Laos', 'code' => 'LA', 'lang' => strtolower('LA'), 'phone_code' => '856', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '120',  'name' => 'Latvia', 'code' => 'LV', 'lang' => strtolower('LV'), 'phone_code' => '371', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '121',  'name' => 'Lebanon', 'code' => 'LB', 'lang' => strtolower('LB'), 'phone_code' => '961', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '122',  'name' => 'Lesotho', 'code' => 'LS', 'lang' => strtolower('LS'), 'phone_code' => '266', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '123',  'name' => 'Liberia', 'code' => 'LR', 'lang' => strtolower('LR'), 'phone_code' => '231', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '124',  'name' => 'Libya', 'code' => 'LY', 'lang' => strtolower('LY'), 'phone_code' => '218', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '125',  'name' => 'Liechtenstein', 'code' => 'LI', 'lang' => strtolower('LI'), 'phone_code' => '423', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '126',  'name' => 'Lithuania', 'code' => 'LT', 'lang' => strtolower('LT'), 'phone_code' => '370', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '127',  'name' => 'Luxembourg', 'code' => 'LU', 'lang' => strtolower('LU'), 'phone_code' => '352', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '128',  'name' => 'Macau S.A.R.', 'code' => 'MO', 'lang' => strtolower('MO'), 'phone_code' => '853', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '129',  'name' => 'Macedonia', 'code' => 'MK', 'lang' => strtolower('MK'), 'phone_code' => '389', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '130',  'name' => 'Madagascar', 'code' => 'MG', 'lang' => strtolower('MG'), 'phone_code' => '261', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '131',  'name' => 'Malawi', 'code' => 'MW', 'lang' => strtolower('MW'), 'phone_code' => '265', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '132',  'name' => 'Malaysia', 'code' => 'MY', 'lang' => strtolower('MY'), 'phone_code' => '60', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '133',  'name' => 'Maldives', 'code' => 'MV', 'lang' => strtolower('MV'), 'phone_code' => '960', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '134',  'name' => 'Mali', 'code' => 'ML', 'lang' => strtolower('ML'), 'phone_code' => '223', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '135',  'name' => 'Malta', 'code' => 'MT', 'lang' => strtolower('MT'), 'phone_code' => '356', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '136',  'name' => 'Man (Isle of)', 'code' => 'XM', 'lang' => strtolower('XM'), 'phone_code' => '44', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '137',  'name' => 'Marshall Islands', 'code' => 'MH', 'lang' => strtolower('MH'), 'phone_code' => '692', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '138',  'name' => 'Martinique', 'code' => 'MQ', 'lang' => strtolower('MQ'), 'phone_code' => '596', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '139',  'name' => 'Mauritania', 'code' => 'MR', 'lang' => strtolower('MR'), 'phone_code' => '222', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '140',  'name' => 'Mauritius', 'code' => 'MU', 'lang' => strtolower('MU'), 'phone_code' => '230', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '141',  'name' => 'Mayotte', 'code' => 'YT', 'lang' => strtolower('YT'), 'phone_code' => '269', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '142',  'name' => 'Mexico', 'code' => 'MX', 'lang' => strtolower('MX'), 'phone_code' => '52', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '143',  'name' => 'Micronesia', 'code' => 'FM', 'lang' => strtolower('FM'), 'phone_code' => '691', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '144',  'name' => 'Moldova', 'code' => 'MD', 'lang' => strtolower('MD'), 'phone_code' => '373', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '145',  'name' => 'Monaco', 'code' => 'MC', 'lang' => strtolower('MC'), 'phone_code' => '377', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '146',  'name' => 'Mongolia', 'code' => 'MN', 'lang' => strtolower('MN'), 'phone_code' => '976', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '147',  'name' => 'Montserrat', 'code' => 'MS', 'lang' => strtolower('MS'), 'phone_code' => '1664', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '148',  'name' => 'Morocco', 'code' => 'MA', 'lang' => strtolower('MA'), 'phone_code' => '212', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '149',  'name' => 'Mozambique', 'code' => 'MZ', 'lang' => strtolower('MZ'), 'phone_code' => '258', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '150',  'name' => 'Myanmar', 'code' => 'MM', 'lang' => strtolower('MM'), 'phone_code' => '95', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '151',  'name' => 'Namibia', 'code' => 'NA', 'lang' => strtolower('NA'), 'phone_code' => '264', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '152',  'name' => 'Nauru', 'code' => 'NR', 'lang' => strtolower('NR'), 'phone_code' => '674', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '153',  'name' => 'Nepal', 'code' => 'NP', 'lang' => strtolower('NP'), 'phone_code' => '977', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '154',  'name' => 'Netherlands Antilles', 'code' => 'AN', 'lang' => strtolower('AN'), 'phone_code' => '599', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '155',  'name' => 'Netherlands The', 'code' => 'NL', 'lang' => strtolower('NL'), 'phone_code' => '31', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '156',  'name' => 'New Caledonia', 'code' => 'NC', 'lang' => strtolower('NC'), 'phone_code' => '687', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '157',  'name' => 'New Zealand', 'code' => 'NZ', 'lang' => strtolower('NZ'), 'phone_code' => '64', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '158',  'name' => 'Nicaragua', 'code' => 'NI', 'lang' => strtolower('NI'), 'phone_code' => '505', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '159',  'name' => 'Niger', 'code' => 'NE', 'lang' => strtolower('NE'), 'phone_code' => '227', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '160',  'name' => 'Nigeria', 'code' => 'NG', 'lang' => strtolower('NG'), 'phone_code' => '234', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '161',  'name' => 'Niue', 'code' => 'NU', 'lang' => strtolower('NU'), 'phone_code' => '683', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '162',  'name' => 'Norfolk Island', 'code' => 'NF', 'lang' => strtolower('NF'), 'phone_code' => '672', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '163',  'name' => 'Northern Mariana Islands', 'code' => 'MP', 'lang' => strtolower('MP'), 'phone_code' => '1670', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '164',  'name' => 'Norway', 'code' => 'NO', 'lang' => strtolower('NO'), 'phone_code' => '47', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '165',  'name' => 'Oman', 'code' => 'OM', 'lang' => strtolower('ar'), 'phone_code' => '968', 'color' => '#13fc03', 'is_active' => 1, 'created_at' => $now],
            ['id' => '166',  'name' => 'Pakistan', 'code' => 'PK', 'lang' => strtolower('PK'), 'phone_code' => '92', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '167',  'name' => 'Palau', 'code' => 'PW', 'lang' => strtolower('PW'), 'phone_code' => '680', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '168',  'name' => 'Palestinian Territory Occupied', 'code' => 'PS', 'lang' => strtolower('PS'), 'phone_code' => '970', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '169',  'name' => 'Panama', 'code' => 'PA', 'lang' => strtolower('PA'), 'phone_code' => '507', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '170',  'name' => 'Papua new Guinea', 'code' => 'PG', 'lang' => strtolower('PG'), 'phone_code' => '675', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '171',  'name' => 'Paraguay', 'code' => 'PY', 'lang' => strtolower('PY'), 'phone_code' => '595', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '172',  'name' => 'Peru', 'code' => 'PE', 'lang' => strtolower('PE'), 'phone_code' => '51', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '173',  'name' => 'Philippines', 'code' => 'PH', 'lang' => strtolower('PH'), 'phone_code' => '63', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '174',  'name' => 'Pitcairn Island', 'code' => 'PN', 'lang' => strtolower('PN'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '175',  'name' => 'Poland', 'code' => 'PL', 'lang' => strtolower('PL'), 'phone_code' => '48', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '176',  'name' => 'Portugal', 'code' => 'PT', 'lang' => strtolower('PT'), 'phone_code' => '351', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '177',  'name' => 'Puerto Rico', 'code' => 'PR', 'lang' => strtolower('PR'), 'phone_code' => '1787', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '178',  'name' => 'Qatar', 'code' => 'QA', 'lang' => strtolower('QA'), 'phone_code' => '974', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '179',  'name' => 'Reunion', 'code' => 'RE', 'lang' => strtolower('RE'), 'phone_code' => '262', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '180',  'name' => 'Romania', 'code' => 'RO', 'lang' => strtolower('RO'), 'phone_code' => '40', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '181',  'name' => 'Russia', 'code' => 'RU', 'lang' => strtolower('RU'), 'phone_code' => '70', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '182',  'name' => 'Rwanda', 'code' => 'RW', 'lang' => strtolower('RW'), 'phone_code' => '250', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '183',  'name' => 'Saint Helena', 'code' => 'SH', 'lang' => strtolower('SH'), 'phone_code' => '290', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '184',  'name' => 'Saint Kitts And Nevis', 'code' => 'KN', 'lang' => strtolower('KN'), 'phone_code' => '1869', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '185',  'name' => 'Saint Lucia', 'code' => 'LC', 'lang' => strtolower('LC'), 'phone_code' => '1758', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '186',  'name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'lang' => strtolower('PM'), 'phone_code' => '508', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '187',  'name' => 'Saint Vincent And The Grenadines', 'code' => 'VC', 'lang' => strtolower('VC'), 'phone_code' => '1784', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '188',  'name' => 'Samoa', 'code' => 'WS', 'lang' => strtolower('WS'), 'phone_code' => '684', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '189',  'name' => 'San Marino', 'code' => 'SM', 'lang' => strtolower('SM'), 'phone_code' => '378', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '190',  'name' => 'Sao Tome and Principe', 'code' => 'ST', 'lang' => strtolower('ST'), 'phone_code' => '239', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '191',  'name' => 'Saudi Arabia', 'code' => 'SA', 'lang' => strtolower('SA'), 'phone_code' => '966', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '192',  'name' => 'Senegal', 'code' => 'SN', 'lang' => strtolower('SN'), 'phone_code' => '221', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '193',  'name' => 'Serbia', 'code' => 'RS', 'lang' => strtolower('RS'), 'phone_code' => '381', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '194',  'name' => 'Seychelles', 'code' => 'SC', 'lang' => strtolower('SC'), 'phone_code' => '248', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '195',  'name' => 'Sierra Leone', 'code' => 'SL', 'lang' => strtolower('SL'), 'phone_code' => '232', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '196',  'name' => 'Singapore', 'code' => 'SG', 'lang' => strtolower('SG'), 'phone_code' => '65', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '197',  'name' => 'Slovakia', 'code' => 'SK', 'lang' => strtolower('SK'), 'phone_code' => '421', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '198',  'name' => 'Slovenia', 'code' => 'SI', 'lang' => strtolower('SI'), 'phone_code' => '386', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '199',  'name' => 'Smaller Territories of the UK', 'code' => 'XG', 'lang' => strtolower('XG'), 'phone_code' => '44', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '200',  'name' => 'Solomon Islands', 'code' => 'SB', 'lang' => strtolower('SB'), 'phone_code' => '677', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '201',  'name' => 'Somalia', 'code' => 'SO', 'lang' => strtolower('SO'), 'phone_code' => '252', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '202',  'name' => 'South Africa', 'code' => 'ZA', 'lang' => strtolower('ZA'), 'phone_code' => '27', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '203',  'name' => 'South Georgia', 'code' => 'GS', 'lang' => strtolower('GS'), 'phone_code' => '0', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '204',  'name' => 'South Sudan', 'code' => 'SS', 'lang' => strtolower('SS'), 'phone_code' => '211', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '205',  'name' => 'Spain', 'code' => 'ES', 'lang' => strtolower('ES'), 'phone_code' => '34', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '206',  'name' => 'Sri Lanka', 'code' => 'LK', 'lang' => strtolower('LK'), 'phone_code' => '94', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '207',  'name' => 'Sudan', 'code' => 'SD', 'lang' => strtolower('SD'), 'phone_code' => '249', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '208',  'name' => 'Suriname', 'code' => 'SR', 'lang' => strtolower('SR'), 'phone_code' => '597', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '209',  'name' => 'Svalbard And Jan Mayen Islands', 'code' => 'SJ', 'lang' => strtolower('SJ'), 'phone_code' => '47', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '210',  'name' => 'Swaziland', 'code' => 'SZ', 'lang' => strtolower('SZ'), 'phone_code' => '268', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '211',  'name' => 'Sweden', 'code' => 'SE', 'lang' => strtolower('SE'), 'phone_code' => '46', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '212',  'name' => 'Switzerland', 'code' => 'CH', 'lang' => strtolower('CH'), 'phone_code' => '41', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '213',  'name' => 'Syria', 'code' => 'SY', 'lang' => strtolower('SY'), 'phone_code' => '963', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '214',  'name' => 'Taiwan', 'code' => 'TW', 'lang' => strtolower('TW'), 'phone_code' => '886', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '215',  'name' => 'Tajikistan', 'code' => 'TJ', 'lang' => strtolower('TJ'), 'phone_code' => '992', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '216',  'name' => 'Tanzania', 'code' => 'TZ', 'lang' => strtolower('TZ'), 'phone_code' => '255', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '217',  'name' => 'Thailand', 'code' => 'TH', 'lang' => strtolower('TH'), 'phone_code' => '66', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '218',  'name' => 'Togo', 'code' => 'TG', 'lang' => strtolower('TG'), 'phone_code' => '228', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '219',  'name' => 'Tokelau', 'code' => 'TK', 'lang' => strtolower('TK'), 'phone_code' => '690', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '220',  'name' => 'Tonga', 'code' => 'TO', 'lang' => strtolower('TO'), 'phone_code' => '676', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '221',  'name' => 'Trinidad And Tobago', 'code' => 'TT', 'lang' => strtolower('TT'), 'phone_code' => '1868', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '222',  'name' => 'Tunisia', 'code' => 'TN', 'lang' => strtolower('TN'), 'phone_code' => '216', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '223',  'name' => 'Turkey', 'code' => 'TR', 'lang' => strtolower('TR'), 'phone_code' => '90', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '224',  'name' => 'Turkmenistan', 'code' => 'TM', 'lang' => strtolower('TM'), 'phone_code' => '7370', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '225',  'name' => 'Turks And Caicos Islands', 'code' => 'TC', 'lang' => strtolower('TC'), 'phone_code' => '1649', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '226',  'name' => 'Tuvalu', 'code' => 'TV', 'lang' => strtolower('TV'), 'phone_code' => '688', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '227',  'name' => 'Uganda', 'code' => 'UG', 'lang' => strtolower('UG'), 'phone_code' => '256', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '228',  'name' => 'Ukraine', 'code' => 'UA', 'lang' => strtolower('UA'), 'phone_code' => '380', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '229',  'name' => 'United Arab Emirates', 'code' => 'AE', 'lang' => strtolower('AE'), 'phone_code' => '971', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '230',  'name' => 'United Kingdom', 'code' => 'GB', 'lang' => strtolower('GB'), 'phone_code' => '44', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '231',  'name' => 'United States', 'code' => 'US', 'lang' => strtolower('en'), 'phone_code' => '1', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '232',  'name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'lang' => strtolower('UM'), 'phone_code' => '1', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '233',  'name' => 'Uruguay', 'code' => 'UY', 'lang' => strtolower('UY'), 'phone_code' => '598', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '234',  'name' => 'Uzbekistan', 'code' => 'UZ', 'lang' => strtolower('UZ'), 'phone_code' => '998', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '235',  'name' => 'Vanuatu', 'code' => 'VU', 'lang' => strtolower('VU'), 'phone_code' => '678', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '236',  'name' => 'Vatican City State (Holy See)', 'code' => 'VA', 'lang' => strtolower('VA'), 'phone_code' => '39', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '237',  'name' => 'Venezuela', 'code' => 'VE', 'lang' => strtolower('VE'), 'phone_code' => '58', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '238',  'name' => 'Vietnam', 'code' => 'VN', 'lang' => strtolower('VN'), 'phone_code' => '84', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '239',  'name' => 'Virgin Islands (British)', 'code' => 'VG', 'lang' => strtolower('VG'), 'phone_code' => '1284', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '240',  'name' => 'Virgin Islands (US)', 'code' => 'VI', 'lang' => strtolower('VI'), 'phone_code' => '1340', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '241',  'name' => 'Wallis And Futuna Islands', 'code' => 'WF', 'lang' => strtolower('WF'), 'phone_code' => '681', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '242',  'name' => 'Western Sahara', 'code' => 'EH', 'lang' => strtolower('EH'), 'phone_code' => '212', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '243',  'name' => 'Yemen', 'code' => 'YE', 'lang' => strtolower('YE'), 'phone_code' => '967', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '244',  'name' => 'Yugoslavia', 'code' => 'YU', 'lang' => strtolower('YU'), 'phone_code' => '38', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '245',  'name' => 'Zambia', 'code' => 'ZM', 'lang' => strtolower('ZM'), 'phone_code' => '260', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
            ['id' => '246',  'name' => 'Zimbabwe', 'code' => 'ZW', 'lang' => strtolower('ZW'), 'phone_code' => '263', 'color' => '#000', 'is_active' => 0, 'created_at' => $now],
        ];

        Country::insert($country);

        $media = [];
        $medium_items = [];

        foreach ($country as $row) {
            $code = strtolower($row['code']);
            $media[] = [
                'path' => "public/media/flags/$code.png",
                'mime_type' => 'image/png'
            ];
            $medium_items[] = [
                'name' => 'flag',
                'medium_id' => $row['id'],
                'media_item_type' => 'App\Model\Country',
                'media_item_id' => $row['id']
            ];
        }

        DB::table('media')->insert($media);
        DB::table('medium_items')->insert($medium_items);
    }
}
