<?php

use App\Model\Country;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::disableQueryLog();
        DB::table('countries')->delete();

        $country = [
            ['id' => '1',  'name' => 'Afghanistan', 'code' => 'AF', 'phone_code' => '93', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '2',  'name' => 'Albania', 'code' => 'AL', 'phone_code' => '355', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '3',  'name' => 'Algeria', 'code' => 'DZ', 'phone_code' => '213', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '4',  'name' => 'American Samoa', 'code' => 'AS', 'phone_code' => '1684', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '5',  'name' => 'Andorra', 'code' => 'AD', 'phone_code' => '376', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '6',  'name' => 'Angola', 'code' => 'AO', 'phone_code' => '244', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '7',  'name' => 'Anguilla', 'code' => 'AI', 'phone_code' => '1264', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '8',  'name' => 'Antarctica', 'code' => 'AQ', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '9',  'name' => 'Antigua And Barbuda', 'code' => 'AG', 'phone_code' => '1268', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '10',  'name' => 'Argentina', 'code' => 'AR', 'phone_code' => '54', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '11',  'name' => 'Armenia', 'code' => 'AM', 'phone_code' => '374', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '12',  'name' => 'Aruba', 'code' => 'AW', 'phone_code' => '297', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '13',  'name' => 'Australia', 'code' => 'AU', 'phone_code' => '61', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '14',  'name' => 'Austria', 'code' => 'AT', 'phone_code' => '43', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '15',  'name' => 'Azerbaijan', 'code' => 'AZ', 'phone_code' => '994', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '16',  'name' => 'Bahamas The', 'code' => 'BS', 'phone_code' => '1242', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '17',  'name' => 'Bahrain', 'code' => 'BH', 'phone_code' => '973', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '18',  'name' => 'Bangladesh', 'code' => 'BD', 'phone_code' => '880', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '19',  'name' => 'Barbados', 'code' => 'BB', 'phone_code' => '1246', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '20',  'name' => 'Belarus', 'code' => 'BY', 'phone_code' => '375', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '21',  'name' => 'Belgium', 'code' => 'BE', 'phone_code' => '32', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '22',  'name' => 'Belize', 'code' => 'BZ', 'phone_code' => '501', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '23',  'name' => 'Benin', 'code' => 'BJ', 'phone_code' => '229', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '24',  'name' => 'Bermuda', 'code' => 'BM', 'phone_code' => '1441', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '25',  'name' => 'Bhutan', 'code' => 'BT', 'phone_code' => '975', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '26',  'name' => 'Bolivia', 'code' => 'BO', 'phone_code' => '591', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '27',  'name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'phone_code' => '387', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '28',  'name' => 'Botswana', 'code' => 'BW', 'phone_code' => '267', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '29',  'name' => 'Bouvet Island', 'code' => 'BV', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '30',  'name' => 'Brazil', 'code' => 'BR', 'phone_code' => '55', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '31',  'name' => 'British Indian Ocean Territory', 'code' => 'IO', 'phone_code' => '246', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '32',  'name' => 'Brunei', 'code' => 'BN', 'phone_code' => '673', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '33',  'name' => 'Bulgaria', 'code' => 'BG', 'phone_code' => '359', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '34',  'name' => 'Burkina Faso', 'code' => 'BF', 'phone_code' => '226', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '35',  'name' => 'Burundi', 'code' => 'BI', 'phone_code' => '257', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '36',  'name' => 'Cambodia', 'code' => 'KH', 'phone_code' => '855', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '37',  'name' => 'Cameroon', 'code' => 'CM', 'phone_code' => '237', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '38',  'name' => 'Canada', 'code' => 'CA', 'phone_code' => '1', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '39',  'name' => 'Cape Verde', 'code' => 'CV', 'phone_code' => '238', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '40',  'name' => 'Cayman Islands', 'code' => 'KY', 'phone_code' => '1345', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '41',  'name' => 'Central African Republic', 'code' => 'CF', 'phone_code' => '236', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '42',  'name' => 'Chad', 'code' => 'TD', 'phone_code' => '235', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '43',  'name' => 'Chile', 'code' => 'CL', 'phone_code' => '56', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '44',  'name' => 'China', 'code' => 'CN', 'phone_code' => '86', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '45',  'name' => 'Christmas Island', 'code' => 'CX', 'phone_code' => '61', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '46',  'name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'phone_code' => '672', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '47',  'name' => 'Colombia', 'code' => 'CO', 'phone_code' => '57', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '48',  'name' => 'Comoros', 'code' => 'KM', 'phone_code' => '269', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '49',  'name' => 'Republic Of The Congo', 'code' => 'CG', 'phone_code' => '242', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '50',  'name' => 'Democratic Republic Of The Congo', 'code' => 'CD', 'phone_code' => '242', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '51',  'name' => 'Cook Islands', 'code' => 'CK', 'phone_code' => '682', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '52',  'name' => 'Costa Rica', 'code' => 'CR', 'phone_code' => '506', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '53',  'name' => 'Cote D\'Ivoire (Ivory Coast)', 'code' => 'CI', 'phone_code' => '225', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '54',  'name' => 'Croatia (Hrvatska)', 'code' => 'HR', 'phone_code' => '385', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '55',  'name' => 'Cuba', 'code' => 'CU', 'phone_code' => '53', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '56',  'name' => 'Cyprus', 'code' => 'CY', 'phone_code' => '357', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '57',  'name' => 'Czech Republic', 'code' => 'CZ', 'phone_code' => '420', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '58',  'name' => 'Denmark', 'code' => 'DK', 'phone_code' => '45', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '59',  'name' => 'Djibouti', 'code' => 'DJ', 'phone_code' => '253', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '60',  'name' => 'Dominica', 'code' => 'DM', 'phone_code' => '1767', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '61',  'name' => 'Dominican Republic', 'code' => 'DO', 'phone_code' => '1809', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '62',  'name' => 'East Timor', 'code' => 'TP', 'phone_code' => '670', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '63',  'name' => 'Ecuador', 'code' => 'EC', 'phone_code' => '593', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '64',  'name' => 'Egypt', 'code' => 'EG', 'phone_code' => '20', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '65',  'name' => 'El Salvador', 'code' => 'SV', 'phone_code' => '503', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '66',  'name' => 'Equatorial Guinea', 'code' => 'GQ', 'phone_code' => '240', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '67',  'name' => 'Eritrea', 'code' => 'ER', 'phone_code' => '291', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '68',  'name' => 'Estonia', 'code' => 'EE', 'phone_code' => '372', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '69',  'name' => 'Ethiopia', 'code' => 'ET', 'phone_code' => '251', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '70',  'name' => 'External Territories of Australia', 'code' => 'XA', 'phone_code' => '61', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '71',  'name' => 'Falkland Islands', 'code' => 'FK', 'phone_code' => '500', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '72',  'name' => 'Faroe Islands', 'code' => 'FO', 'phone_code' => '298', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '73',  'name' => 'Fiji Islands', 'code' => 'FJ', 'phone_code' => '679', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '74',  'name' => 'Finland', 'code' => 'FI', 'phone_code' => '358', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '75',  'name' => 'France', 'code' => 'FR', 'phone_code' => '33', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '76',  'name' => 'French Guiana', 'code' => 'GF', 'phone_code' => '594', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '77',  'name' => 'French Polynesia', 'code' => 'PF', 'phone_code' => '689', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '78',  'name' => 'French Southern Territories', 'code' => 'TF', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '79',  'name' => 'Gabon', 'code' => 'GA', 'phone_code' => '241', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '80',  'name' => 'Gambia The', 'code' => 'GM', 'phone_code' => '220', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '81',  'name' => 'Georgia', 'code' => 'GE', 'phone_code' => '995', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '82',  'name' => 'Germany', 'code' => 'DE', 'phone_code' => '49', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '83',  'name' => 'Ghana', 'code' => 'GH', 'phone_code' => '233', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '84',  'name' => 'Gibraltar', 'code' => 'GI', 'phone_code' => '350', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '85',  'name' => 'Greece', 'code' => 'GR', 'phone_code' => '30', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '86',  'name' => 'Greenland', 'code' => 'GL', 'phone_code' => '299', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '87',  'name' => 'Grenada', 'code' => 'GD', 'phone_code' => '1473', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '88',  'name' => 'Guadeloupe', 'code' => 'GP', 'phone_code' => '590', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '89',  'name' => 'Guam', 'code' => 'GU', 'phone_code' => '1671', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '90',  'name' => 'Guatemala', 'code' => 'GT', 'phone_code' => '502', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '91',  'name' => 'Guernsey and Alderney', 'code' => 'XU', 'phone_code' => '44', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '92',  'name' => 'Guinea', 'code' => 'GN', 'phone_code' => '224', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '93',  'name' => 'Guinea-Bissau', 'code' => 'GW', 'phone_code' => '245', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '94',  'name' => 'Guyana', 'code' => 'GY', 'phone_code' => '592', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '95',  'name' => 'Haiti', 'code' => 'HT', 'phone_code' => '509', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '96',  'name' => 'Heard and McDonald Islands', 'code' => 'HM', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '97',  'name' => 'Honduras', 'code' => 'HN', 'phone_code' => '504', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '98',  'name' => 'Hong Kong S.A.R.', 'code' => 'HK', 'phone_code' => '852', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '99',  'name' => 'Hungary', 'code' => 'HU', 'phone_code' => '36', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '100',  'name' => 'Iceland', 'code' => 'IS', 'phone_code' => '354', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '101',  'name' => 'India', 'code' => 'IN', 'phone_code' => '91', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '102',  'name' => 'Indonesia', 'code' => 'ID', 'phone_code' => '62', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '103',  'name' => 'Iran', 'code' => 'IR', 'phone_code' => '98', 'isActive' => 1, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '104',  'name' => 'Iraq', 'code' => 'IQ', 'phone_code' => '964', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '105',  'name' => 'Ireland', 'code' => 'IE', 'phone_code' => '353', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '106',  'name' => 'Israel', 'code' => 'IL', 'phone_code' => '972', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '107',  'name' => 'Italy', 'code' => 'IT', 'phone_code' => '39', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '108',  'name' => 'Jamaica', 'code' => 'JM', 'phone_code' => '1876', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '109',  'name' => 'Japan', 'code' => 'JP', 'phone_code' => '81', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '110',  'name' => 'Jersey', 'code' => 'XJ', 'phone_code' => '44', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '111',  'name' => 'Jordan', 'code' => 'JO', 'phone_code' => '962', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '112',  'name' => 'Kazakhstan', 'code' => 'KZ', 'phone_code' => '7', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '113',  'name' => 'Kenya', 'code' => 'KE', 'phone_code' => '254', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '114',  'name' => 'Kiribati', 'code' => 'KI', 'phone_code' => '686', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '115',  'name' => 'Korea North', 'code' => 'KP', 'phone_code' => '850', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '116',  'name' => 'Korea South', 'code' => 'KR', 'phone_code' => '82', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '117',  'name' => 'Kuwait', 'code' => 'KW', 'phone_code' => '965', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '118',  'name' => 'Kyrgyzstan', 'code' => 'KG', 'phone_code' => '996', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '119',  'name' => 'Laos', 'code' => 'LA', 'phone_code' => '856', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '120',  'name' => 'Latvia', 'code' => 'LV', 'phone_code' => '371', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '121',  'name' => 'Lebanon', 'code' => 'LB', 'phone_code' => '961', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '122',  'name' => 'Lesotho', 'code' => 'LS', 'phone_code' => '266', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '123',  'name' => 'Liberia', 'code' => 'LR', 'phone_code' => '231', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '124',  'name' => 'Libya', 'code' => 'LY', 'phone_code' => '218', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '125',  'name' => 'Liechtenstein', 'code' => 'LI', 'phone_code' => '423', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '126',  'name' => 'Lithuania', 'code' => 'LT', 'phone_code' => '370', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '127',  'name' => 'Luxembourg', 'code' => 'LU', 'phone_code' => '352', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '128',  'name' => 'Macau S.A.R.', 'code' => 'MO', 'phone_code' => '853', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '129',  'name' => 'Macedonia', 'code' => 'MK', 'phone_code' => '389', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '130',  'name' => 'Madagascar', 'code' => 'MG', 'phone_code' => '261', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '131',  'name' => 'Malawi', 'code' => 'MW', 'phone_code' => '265', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '132',  'name' => 'Malaysia', 'code' => 'MY', 'phone_code' => '60', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '133',  'name' => 'Maldives', 'code' => 'MV', 'phone_code' => '960', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '134',  'name' => 'Mali', 'code' => 'ML', 'phone_code' => '223', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '135',  'name' => 'Malta', 'code' => 'MT', 'phone_code' => '356', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '136',  'name' => 'Man (Isle of)', 'code' => 'XM', 'phone_code' => '44', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '137',  'name' => 'Marshall Islands', 'code' => 'MH', 'phone_code' => '692', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '138',  'name' => 'Martinique', 'code' => 'MQ', 'phone_code' => '596', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '139',  'name' => 'Mauritania', 'code' => 'MR', 'phone_code' => '222', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '140',  'name' => 'Mauritius', 'code' => 'MU', 'phone_code' => '230', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '141',  'name' => 'Mayotte', 'code' => 'YT', 'phone_code' => '269', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '142',  'name' => 'Mexico', 'code' => 'MX', 'phone_code' => '52', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '143',  'name' => 'Micronesia', 'code' => 'FM', 'phone_code' => '691', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '144',  'name' => 'Moldova', 'code' => 'MD', 'phone_code' => '373', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '145',  'name' => 'Monaco', 'code' => 'MC', 'phone_code' => '377', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '146',  'name' => 'Mongolia', 'code' => 'MN', 'phone_code' => '976', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '147',  'name' => 'Montserrat', 'code' => 'MS', 'phone_code' => '1664', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '148',  'name' => 'Morocco', 'code' => 'MA', 'phone_code' => '212', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '149',  'name' => 'Mozambique', 'code' => 'MZ', 'phone_code' => '258', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '150',  'name' => 'Myanmar', 'code' => 'MM', 'phone_code' => '95', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '151',  'name' => 'Namibia', 'code' => 'NA', 'phone_code' => '264', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '152',  'name' => 'Nauru', 'code' => 'NR', 'phone_code' => '674', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '153',  'name' => 'Nepal', 'code' => 'NP', 'phone_code' => '977', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '154',  'name' => 'Netherlands Antilles', 'code' => 'AN', 'phone_code' => '599', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '155',  'name' => 'Netherlands The', 'code' => 'NL', 'phone_code' => '31', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '156',  'name' => 'New Caledonia', 'code' => 'NC', 'phone_code' => '687', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '157',  'name' => 'New Zealand', 'code' => 'NZ', 'phone_code' => '64', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '158',  'name' => 'Nicaragua', 'code' => 'NI', 'phone_code' => '505', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '159',  'name' => 'Niger', 'code' => 'NE', 'phone_code' => '227', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '160',  'name' => 'Nigeria', 'code' => 'NG', 'phone_code' => '234', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '161',  'name' => 'Niue', 'code' => 'NU', 'phone_code' => '683', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '162',  'name' => 'Norfolk Island', 'code' => 'NF', 'phone_code' => '672', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '163',  'name' => 'Northern Mariana Islands', 'code' => 'MP', 'phone_code' => '1670', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '164',  'name' => 'Norway', 'code' => 'NO', 'phone_code' => '47', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '165',  'name' => 'Oman', 'code' => 'OM', 'phone_code' => '968', 'isActive' => 1, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '166',  'name' => 'Pakistan', 'code' => 'PK', 'phone_code' => '92', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '167',  'name' => 'Palau', 'code' => 'PW', 'phone_code' => '680', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '168',  'name' => 'Palestinian Territory Occupied', 'code' => 'PS', 'phone_code' => '970', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '169',  'name' => 'Panama', 'code' => 'PA', 'phone_code' => '507', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '170',  'name' => 'Papua new Guinea', 'code' => 'PG', 'phone_code' => '675', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '171',  'name' => 'Paraguay', 'code' => 'PY', 'phone_code' => '595', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '172',  'name' => 'Peru', 'code' => 'PE', 'phone_code' => '51', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '173',  'name' => 'Philippines', 'code' => 'PH', 'phone_code' => '63', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '174',  'name' => 'Pitcairn Island', 'code' => 'PN', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '175',  'name' => 'Poland', 'code' => 'PL', 'phone_code' => '48', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '176',  'name' => 'Portugal', 'code' => 'PT', 'phone_code' => '351', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '177',  'name' => 'Puerto Rico', 'code' => 'PR', 'phone_code' => '1787', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '178',  'name' => 'Qatar', 'code' => 'QA', 'phone_code' => '974', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '179',  'name' => 'Reunion', 'code' => 'RE', 'phone_code' => '262', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '180',  'name' => 'Romania', 'code' => 'RO', 'phone_code' => '40', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '181',  'name' => 'Russia', 'code' => 'RU', 'phone_code' => '70', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '182',  'name' => 'Rwanda', 'code' => 'RW', 'phone_code' => '250', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '183',  'name' => 'Saint Helena', 'code' => 'SH', 'phone_code' => '290', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '184',  'name' => 'Saint Kitts And Nevis', 'code' => 'KN', 'phone_code' => '1869', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '185',  'name' => 'Saint Lucia', 'code' => 'LC', 'phone_code' => '1758', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '186',  'name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'phone_code' => '508', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '187',  'name' => 'Saint Vincent And The Grenadines', 'code' => 'VC', 'phone_code' => '1784', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '188',  'name' => 'Samoa', 'code' => 'WS', 'phone_code' => '684', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '189',  'name' => 'San Marino', 'code' => 'SM', 'phone_code' => '378', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '190',  'name' => 'Sao Tome and Principe', 'code' => 'ST', 'phone_code' => '239', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '191',  'name' => 'Saudi Arabia', 'code' => 'SA', 'phone_code' => '966', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '192',  'name' => 'Senegal', 'code' => 'SN', 'phone_code' => '221', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '193',  'name' => 'Serbia', 'code' => 'RS', 'phone_code' => '381', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '194',  'name' => 'Seychelles', 'code' => 'SC', 'phone_code' => '248', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '195',  'name' => 'Sierra Leone', 'code' => 'SL', 'phone_code' => '232', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '196',  'name' => 'Singapore', 'code' => 'SG', 'phone_code' => '65', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '197',  'name' => 'Slovakia', 'code' => 'SK', 'phone_code' => '421', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '198',  'name' => 'Slovenia', 'code' => 'SI', 'phone_code' => '386', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '199',  'name' => 'Smaller Territories of the UK', 'code' => 'XG', 'phone_code' => '44', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '200',  'name' => 'Solomon Islands', 'code' => 'SB', 'phone_code' => '677', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '201',  'name' => 'Somalia', 'code' => 'SO', 'phone_code' => '252', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '202',  'name' => 'South Africa', 'code' => 'ZA', 'phone_code' => '27', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '203',  'name' => 'South Georgia', 'code' => 'GS', 'phone_code' => '0', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '204',  'name' => 'South Sudan', 'code' => 'SS', 'phone_code' => '211', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '205',  'name' => 'Spain', 'code' => 'ES', 'phone_code' => '34', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '206',  'name' => 'Sri Lanka', 'code' => 'LK', 'phone_code' => '94', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '207',  'name' => 'Sudan', 'code' => 'SD', 'phone_code' => '249', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '208',  'name' => 'Suriname', 'code' => 'SR', 'phone_code' => '597', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '209',  'name' => 'Svalbard And Jan Mayen Islands', 'code' => 'SJ', 'phone_code' => '47', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '210',  'name' => 'Swaziland', 'code' => 'SZ', 'phone_code' => '268', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '211',  'name' => 'Sweden', 'code' => 'SE', 'phone_code' => '46', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '212',  'name' => 'Switzerland', 'code' => 'CH', 'phone_code' => '41', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '213',  'name' => 'Syria', 'code' => 'SY', 'phone_code' => '963', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '214',  'name' => 'Taiwan', 'code' => 'TW', 'phone_code' => '886', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '215',  'name' => 'Tajikistan', 'code' => 'TJ', 'phone_code' => '992', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '216',  'name' => 'Tanzania', 'code' => 'TZ', 'phone_code' => '255', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '217',  'name' => 'Thailand', 'code' => 'TH', 'phone_code' => '66', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '218',  'name' => 'Togo', 'code' => 'TG', 'phone_code' => '228', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '219',  'name' => 'Tokelau', 'code' => 'TK', 'phone_code' => '690', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '220',  'name' => 'Tonga', 'code' => 'TO', 'phone_code' => '676', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '221',  'name' => 'Trinidad And Tobago', 'code' => 'TT', 'phone_code' => '1868', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '222',  'name' => 'Tunisia', 'code' => 'TN', 'phone_code' => '216', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '223',  'name' => 'Turkey', 'code' => 'TR', 'phone_code' => '90', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '224',  'name' => 'Turkmenistan', 'code' => 'TM', 'phone_code' => '7370', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '225',  'name' => 'Turks And Caicos Islands', 'code' => 'TC', 'phone_code' => '1649', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '226',  'name' => 'Tuvalu', 'code' => 'TV', 'phone_code' => '688', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '227',  'name' => 'Uganda', 'code' => 'UG', 'phone_code' => '256', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '228',  'name' => 'Ukraine', 'code' => 'UA', 'phone_code' => '380', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '229',  'name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '971', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '230',  'name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '44', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '231',  'name' => 'United States', 'code' => 'US', 'phone_code' => '1', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '232',  'name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'phone_code' => '1', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '233',  'name' => 'Uruguay', 'code' => 'UY', 'phone_code' => '598', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '234',  'name' => 'Uzbekistan', 'code' => 'UZ', 'phone_code' => '998', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '235',  'name' => 'Vanuatu', 'code' => 'VU', 'phone_code' => '678', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '236',  'name' => 'Vatican City State (Holy See)', 'code' => 'VA', 'phone_code' => '39', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '237',  'name' => 'Venezuela', 'code' => 'VE', 'phone_code' => '58', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '238',  'name' => 'Vietnam', 'code' => 'VN', 'phone_code' => '84', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '239',  'name' => 'Virgin Islands (British)', 'code' => 'VG', 'phone_code' => '1284', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '240',  'name' => 'Virgin Islands (US)', 'code' => 'VI', 'phone_code' => '1340', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '241',  'name' => 'Wallis And Futuna Islands', 'code' => 'WF', 'phone_code' => '681', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '242',  'name' => 'Western Sahara', 'code' => 'EH', 'phone_code' => '212', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '243',  'name' => 'Yemen', 'code' => 'YE', 'phone_code' => '967', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '244',  'name' => 'Yugoslavia', 'code' => 'YU', 'phone_code' => '38', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '245',  'name' => 'Zambia', 'code' => 'ZM', 'phone_code' => '260', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
            ['id' => '246',  'name' => 'Zimbabwe', 'code' => 'ZW', 'phone_code' => '263', 'isActive' => 0, 'created_at' => date('Y-m-d H:i:s')],
        ];

        Country::insert($country);

        $media = [];
        $medium_items = [];

        foreach ($country as $row) {
            $code = strtolower($row['code']);
            $media[] = [
                'path' => "public/media/flags/$code.png",
                'mime_type' => 'image/png'
            ];
            $medium_items[] = [
                'name' => 'flag',
                'medium_id' => $row['id'],
                'media_item_type' => 'App\Model\Country',
                'media_item_id' => $row['id']
            ];
        }

        DB::table('media')->insert($media);
        DB::table('medium_items')->insert($medium_items);
    }
}
